# Generated by Django 4.2.11 on 2025-05-09 12:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "subscriptions",
            "0002_alter_plan_options_alter_subscription_options_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="plan",
            old_name="stripe_subscription_id",
            new_name="stripe_price_id",
        ),
        migrations.RemoveField(
            model_name="plan",
            name="certificate_limit",
        ),
        migrations.RemoveField(
            model_name="plan",
            name="created_at",
        ),
        migrations.AddField(
            model_name="plan",
            name="certificate_quota",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="plan",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="plan",
            name="price",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name="subscription",
            name="stripe_subscription_id",
            field=models.CharField(default="", max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="subscription",
            name="certificates_used",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="start_date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
