# Generated by Django 4.2.11 on 2025-05-07 08:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("template_manager", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("subscriptions", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Certificate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "certificate_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("recipient_name", models.CharField(max_length=255)),
                ("recipient_email", models.EmailField(blank=True, max_length=254)),
                ("course_title", models.CharField(max_length=255)),
                ("issue_date", models.DateTimeField(auto_now_add=True)),
                ("expiry_date", models.DateTimeField(blank=True, null=True)),
                (
                    "qr_code_data",
                    models.CharField(
                        blank=True,
                        help_text="Data for QR code verification",
                        max_length=255,
                    ),
                ),
                ("is_valid", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="certificates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "subscription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="certificates",
                        to="subscriptions.subscription",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="certificates",
                        to="template_manager.certificatetemplate",
                    ),
                ),
            ],
            options={
                "ordering": ["-issue_date"],
            },
        ),
    ]
