# Generated by Django 4.2.11 on 2025-05-07 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("template_manager", "0001_initial"),
        ("candidates", "0001_initial"),
        (
            "subscriptions",
            "0002_alter_plan_options_alter_subscription_options_and_more",
        ),
        ("certificates", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="certificate",
            name="qr_code_data",
        ),
        migrations.AddField(
            model_name="certificate",
            name="candidate",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="candidates.candidate",
            ),
        ),
        migrations.AddField(
            model_name="certificate",
            name="qr_code",
            field=models.ImageField(blank=True, null=True, upload_to="qr_codes/"),
        ),
        migrations.AlterField(
            model_name="certificate",
            name="expiry_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="certificate",
            name="issue_date",
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="certificate",
            name="recipient_email",
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name="certificate",
            name="subscription",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="subscriptions.subscription",
            ),
        ),
        migrations.AlterField(
            model_name="certificate",
            name="template",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="template_manager.certificatetemplate",
            ),
        ),
    ]
